spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:orderservicedb
    driverClassName: org.h2.Driver
    username: test
    password: test
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      dll-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
