--todo update customer_id after implementation
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, BILLING_ADDRESS, SHIPPING_ADDRESS, TOTAL_AMOUNT) VALUES (1, 'user1', CURRENT_TIMESTAMP(), 'Eindhoven', 'Eindhoven', 2.7);
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, BILLING_ADDRESS, SHIPPING_ADDRESS, TOTAL_AMOUNT) VALUES (2, 'user2', CURRENT_TIMESTAMP(), 'Eindhoven', 'Eindhoven', 2.8);
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, BILLING_ADDRESS, SHIPPING_ADDRESS, TOTAL_AMOUNT) VALUES (3, 'user1', CURRENT_TIMESTAMP(), 'Eindhoven', 'Eindhoven', 3.6);
INSERT INTO ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES (1, 1, 'nike_1', 'nike shoes', 1.5);
INSERT INTO ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES (2, 1, 'nike_2', 'nike trousers', 1.2);
INSERT INTO ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES (3, 2, 'nike_3', 'nike sweatpants', 1.3);
INSERT INTO ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES (4, 2, 'nike_1', 'nike shoes', 1.5);
INSERT INTO ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES (5, 3, 'nike_4', 'nike t-shirt', 1.6);
INSERT INTO ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES (6, 3, 'adidas_1', 'adidas shoes', 2.0);